### PR TITLE
add reference for socket client into wrapped instance

### PR DESCRIPTION
**Pull request by Twista**
Reference for client should be part of wrappedSocket, in case u will have to access it :)

### CODE REVIEW

**Comment by porn** [comment]
Hey! This is the fix I was looking for! Any chance this will get merged soon?

**Comment by Twista** [comment]
bump! is there anything which is wrong or what i can fix in this PR ?

**Comment by btford** [comment]
duplicate of #97 – please see discussion there

**Comment by Twista** [comment]
ok, after couple issues (means ppl wants it) you just said, you don't like that approach ? is there any "alternative" solution ?

**Pull request closed without merging**
